// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "T-shirt",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #1",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "T-shirt",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #2",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "T-shirt",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #3",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "T-shirt",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #4",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "T-shirt",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #5",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Shoes",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #6",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Shoes",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #7",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Shoes",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #8",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Shoes",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #9",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Shoes",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #10",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "Hat",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #11",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "Hat",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #12",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryName = "Hat",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #13",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryName = "Hat",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #14",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 15L,
                            CategoryName = "Hat",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ImageUrl = "https://placehold.co/400x600",
                            Name = "Product #15",
                            Price = 69.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
